export const ADMIN_MODULE = [
  {
    name: 'adminUserModule',
    description: 'Module for admin user functionalities',
    isActive: true,
    isSystemModule: true,
    created: new Date(),
    modified: new Date(),
    createdBy: 'System',
    // Rutas planas (sin contenedor "Pages") para que el menú las muestre
    // directamente en el primer nivel.
    routes: [
      {
        name: 'Dashboard',
        path: '/pages/dashboard',
        initPath: '/pages/dashboard',
        icon: 'chart-line',
        isActive: true,
        _id: '68e86f941bc240101209cd88',
      },
      {
        name: 'Users',
        path: '/pages/users',
        initPath: '/pages/users',
        icon: 'users',
        isActive: true,
        _id: '68e86f941bc240101209cd89',
      },
      {
        name: 'Sessions',
        path: '/pages/sessions',
        initPath: '/pages/sessions',
        icon: 'desktop',
        isActive: true,
        _id: '68e86f941bc240101209cd8f',
      },
      {
        name: 'Roles',
        path: '/pages/roles',
        initPath: '/pages/roles',
        icon: 'unlock',
        isActive: true,
        _id: '68e86f941bc240101209cd8a',
      },
      {
        name: 'Permissions',
        path: '/pages/permissions',
        initPath: '/pages/permissions',
        icon: 'key',
        isActive: true,
        _id: '68e86f941bc240101209cd8b',
      },
      {
        name: 'Modules',
        path: '/pages/modules',
        initPath: '/pages/modules',
        icon: 'directions',
        isActive: true,
        _id: '68e86f941bc240101209cd8c',
      },
      {
        name: 'Companies',
        path: '/pages/companies',
        initPath: '/pages/companies',
        icon: 'building',
        isActive: true,
        _id: '68e86f941bc240101209cd8d',
      },
      {
        name: 'Políticas',
        path: '/pages/tenant-config',
        initPath: '/pages/tenant-config',
        icon: 'shield',
        isActive: true,
        _id: '68e86f941bc240101209cd8e',
      },
      {
        name: 'Reportes',
        path: '/pages/reports',
        initPath: '/pages/reports',
        icon: 'chart-bar',
        isActive: true,
        _id: '68e86f941bc240101209cd90',
      },
      {
        name: 'Mis sesiones',
        path: '/pages/my-sessions',
        initPath: '/pages/my-sessions',
        icon: 'shield',
        isActive: true,
        _id: '68e86f941bc240101209cd91',
      },
      {
        name: 'Campos personalizados',
        path: '/pages/custom-fields',
        initPath: '/pages/custom-fields',
        icon: 'list',
        isActive: true,
        _id: '68e86f941bc240101209cd92',
      },
    ],
  },
];
